load('DATASET1_1_TEST/mat_ax.mat', 'waveform_ax'); 
fs = 20e6;
waveform = waveform_ax';
x = 10;
% waveform = [zeros(1,x) waveform(1:6800) zeros(1,x) waveform(1:6800) zeros(1,x) waveform(1:6800) zeros(1,x)];
waveform = waveform';

ricianchan = comm.RicianChannel( ...
    'SampleRate',40e6, ...
    'PathDelays',[0.0 0.5 1.2]*1e-6, ...
    'AveragePathGains',[0.1 0.5 0.2], ...
    'KFactor',2.8, ...
    'DirectPathDopplerShift',5.0, ...
    'DirectPathInitialPhase',0.5, ...
    'MaximumDopplerShift',50, ...
    'DopplerSpectrum',doppler('Bell', 8), ...
    'RandomStream','mt19937ar with seed', ...
    'Seed',73, ...
    'PathGainsOutputPort',true);

fadedSignal_ric = ricianchan(waveform);


rayleighchan = comm.RayleighChannel( ...
    'SampleRate',20e6, ...
    'PathDelays',[0 1.5e-4], ...
    'AveragePathGains',[2 3], ...
    'NormalizePathGains',true, ...
    'MaximumDopplerShift',30, ...
    'DopplerSpectrum',{doppler('Gaussian',0.6),doppler('Flat')}, ...
    'RandomStream','mt19937ar with seed', ...
    'Seed',22, ...
    'PathGainsOutputPort',true);

fadedSignal_ray = rayleighchan(waveform);

% fadedSignal_ray = awgn(fadedSignal_ray,-10);


